---
title: "MSnio: Import, export and transformation of spectral data in richly annotated MSnbase"
author:
- name: Michele Stravs
- name: Michael Witting
- name: Hendrik Treutler
package: MSnbase
abstract: This abstract is very abstract
output:
  BiocStyle::html_document:
    toc_float: true
vignette: >
  %\VignetteIndexEntry{MSnio: Import, export and transformation of spectral data}
  %\VignetteEngine{knitr::rmarkdown}
  %%\VignetteKeywords{Mass Spectrometry, MS, MSMS, Metabolomics, Infrastructure, Bioinformatics, quantitative }
  %\VignetteEncoding{UTF-8}
---

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown()
```
Loading the package:
```{r environment, cache=FALSE, echo=FALSE}
library(MSnio)
library(MSnbase)
library(yaml)


```

Processing some data:
```{r processing, cache=FALSE, echo=FALSE}

schema <- yaml.load_file(system.file("schemas/schema_test.yaml", package='MSnio'))
schema_tree <- yaml.load_file(system.file("schemas/schema_test.yaml", package='MSnio'))


# get a spectrum (not really essential in theory)
data("itraqdata")
specs <- as.list(assayData(itraqdata))
sp <- specs[[4]]

# todo: metadata<- etc

sp@metadata <- list(
  name = "Compound",
  compound_class = "natural product",
  formula = "C6H12O6",
  cas = c("666-66-6", "7777-77-7", "8888-88-8"),
  not_mapped = "not_mapped"
)


metadata_identity <- schema_export(sp@metadata, schema)
metadata_identity <- schema_export(sp@metadata, schema, fill=FALSE)

metadata_tree <- schema_export(sp@metadata, schema_tree)
metadata_tree <- schema_export(sp@metadata, schema_tree, fill=FALSE)


metadata_identity_imp <- schema_import(sp@metadata, schema)
metadata_tree_imp <- schema_import(metadata_tree, schema_tree)
```
